obj-m += liquidio-core.o
liquidio-core-y := lio_ethtool.o lio_core.o request_manager.o response_manager.o octeon_device.o cn66xx_device.o cn68xx_device.o cn23xx_pf_device.o cn23xx_vf_device.o octeon_mailbox.o octeon_mem_ops.o octeon_droq.o octeon_nic.o
obj-m += liquidio.o
liquidio-y := lio_main.o octeon_console.o lio_vf_rep.o
